service: los3

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    STEPA_NAME: ${self:custom.stepAName}
    STEPB_NAME: ${self:custom.stepBName}
    STEPC_NAME: ${self:custom.stepCName}
    STEPD_NAME: ${self:custom.stepDName}
    STEPE_NAME: ${self:custom.stepEName}
    STEPF_NAME: ${self:custom.stepFName}
    BUCKET_NAME: ${self:custom.bucketName}

custom:
  stepAName: ${self:service}-${self:provider.stage}-stepA
  stepBName: ${self:service}-${self:provider.stage}-stepB
  stepCName: ${self:service}-${self:provider.stage}-stepC
  stepDName: ${self:service}-${self:provider.stage}-stepD
  stepEName: ${self:service}-${self:provider.stage}-stepE
  stepFName: ${self:service}-${self:provider.stage}-stepF
  bucketName: ds97068los3


functions:
  startProc:
    handler: los3.startProcess
    role: processStartRole
    events:
      - http: POST start-process
  stepA:
    handler: los3.stepA
    name: ${self:service}-${self:provider.stage}-stepA
    role:
      stepRole
  stepB:
    handler: los3.stepB
    name: ${self:service}-${self:provider.stage}-stepB
    role:
      stepRole
  stepC:
    handler: los3.stepC
    name: ${self:service}-${self:provider.stage}-stepC
    role:
      stepRole
  stepD:
    handler: los3.stepD
    name: ${self:service}-${self:provider.stage}-stepD
    role:
      stepRole
  stepE:
    handler: los3.stepE
    name: ${self:service}-${self:provider.stage}-stepE
    role:
      stepRole
  stepF:
    handler: los3.stepF
    name: ${self:service}-${self:provider.stage}-stepF
    role:
      stepRole


resources:
  Resources:
    ProcessInputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        AccessControl: BucketOwnerFullControl

    processStartRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
              - edgelambda.amazonaws.com
            Action:
            - sts:AssumeRole
        Path: "/"
        Policies:
        - PolicyName: logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:*
              Resource: arn:aws:logs:*:*:*
        - PolicyName: s3
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - s3:PutObject
              Resource:
                - 'Fn::Join':
                  - '/'
                  -
                    - Fn::GetAtt: [ ProcessInputBucket, Arn ]
                    - '*'
        - PolicyName: lambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
                - lambda:InvokeAsync
              Resource:
                - "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-stepA"
                - "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-stepB"
                - "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-stepC"
                - "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-stepD"
                - "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-stepE"
                - "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-stepF"

    stepRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
              - edgelambda.amazonaws.com
            Action:
            - sts:AssumeRole
        Path: "/"
        Policies:
        - PolicyName: logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:*
              Resource: arn:aws:logs:*:*:*


plugins:
  - serverless-pseudo-parameters
