service: hello-serverless-stepfns

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: hello.hello

stepFunctions:
  stateMachines:
    hellostepfunc1:
      events:
        - http:
            path: sayhello
            method: post
      definition:
        Comment: "Hello, step functions"
        StartAt: Hello
        States:
          Hello:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-hello"
            End: true


plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
