service: s3processdata

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    BUCKET_NAME: ${self:custom.bucketName}
    STEP_FN_ARN: "arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:ProcessA-${self:provider.stage}"

custom:
  bucketName: ds97068processinput

functions:
  startProc:
    handler: start.startProcess
    role: processStartRole
    events:
      - http: POST start-process
  stepA:
    handler: aprocess.stepA

stepFunctions:
  stateMachines:
    ProcessA:
      name: ProcessA-${opt:stage}
      definition:
        Comment: "A process model"
        StartAt: step-a
        States:
          step-a:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-stepA"
            End: true

resources:
  Resources:
    ProcessInputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        AccessControl: BucketOwnerFullControl
    
    processStartRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
              - edgelambda.amazonaws.com
            Action:
            - sts:AssumeRole
        Path: "/"
        Policies:
        - PolicyName: logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:*
              Resource: arn:aws:logs:*:*:*
        - PolicyName: stepsfns
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - "states:StartExecution"
              Resource:
                - "*"
        - PolicyName: s3
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - s3:PutObject
              Resource:
                - 'Fn::Join':
                  - '/'
                  -
                    - Fn::GetAtt: [ ProcessInputBucket, Arn ]
                    - '*'

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
